# Generated by Django 4.2.4 on 2024-05-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_carrito', models.IntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('finalizado', models.BooleanField(default=False)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.catalogo')),
            ],
        ),
    ]
