version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:  
      - POSTGRES_DB=botiga_prova
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER= usuario # añadir usuario
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: correo@ejemplo.com # añadir correo
      PGADMIN_DEFAULT_PASSWORD: contraseña # añadir contraseña
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: