version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=botiga
     # - POSTGRES_USER=admin #angel user db
     # - POSTGRES_PASSWORD=admin #angel pasword db
      - POSTGRES_USER=sergio #sergio user db
      - POSTGRES_PASSWORD=1234 #sergio pasword db
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "83:80"
    environment:
      # PGADMIN_DEFAULT_EMAIL: 2023_angel.ivanov@iticbcn.cat # angel mail pgadmin4
      # PGADMIN_DEFAULT_PASSWORD: angel123 # angel password pgadmin4
      PGADMIN_DEFAULT_EMAIL: 2023_sergio.castillero@iticbcn.cat # sergio mail pgadmin4
      PGADMIN_DEFAULT_PASSWORD: 235sergioC # sergio password pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: