version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=botiga
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "82:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_angel.ivanov@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: angel123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: