version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:  
      - POSTGRES_DB=botiga
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=sergio
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_sergio.castillero@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: 235sergioC
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: