# Generated by Django 5.0.3 on 2024-04-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSecciones',
            fields=[
                ('id_seccion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.catalogosecciones')),
            ],
        ),
    ]
