# Generated by Django 4.2.4 on 2024-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuarios_contrasena_remove_usuarios_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
